TEMP_FOLDER = "temp"

DEFAULT_LANG = "rus+eng"

UPSCALE_FACTOR = 4
TABLE_UPSCALE_FACTOR = 2

ENABLE_RUSSIAN_CORRECTION = False
ENABLE_ENSEMBLE = True
ENABLE_TABLE_EXTRACTION = True
ENABLE_TEXT_LAYER_FOR_PDF = True

OCR_ZOOM = 5.0
MIN_COMPONENT_AREA = 500